services:
    backend:
        build:
            context: ./backend
        container_name: backend
        restart: always

    frontend:
        build:
            context: ./frontend
            args:
                - VITE_API_URL=${VITE_API_URL}
        container_name: frontend
        ports:
            - "8080:80"
        depends_on:
            - backend
        restart: always
